version: "3.8"
services:
  atcoder_python_env:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    tty: true
    volumes:
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh:ro
      - ${USERPROFILE-~}/work/python3/AtCoder/.git/config:/home/vscode/.gitconfig
      # - ${USERPROFILE-~}/work/python3/AtCoder:/project
    image: atcoder_python_env-image
    container_name: atcoder_python_env-container

