version: "3.3"
services:
  ac-task:
    # build:
    #   context: .
    #   dockerfile: .devcontainer/Dockerfile
    #   args:
    #     - TZ=$acTIMEZONE
    #     - GITNAME=$acGITNAME
    #     - GITEMAIL=$acGITEMAIL
    #   # should edit workspace directory in devcontainer.json when you change USERNAME
    #     - USERNAME=vscode
    #     - USERPASSWD=vscode
    tty: true
    volumes:
      - ${acSSHDIR}/.ssh:/home/vscode/.ssh:ro
      - ./scripts:/home/vscode/scripts
      - ./dotfiles/.vscode:/home/vscode/.vscode
      - ./templates/mytemplate:/home/vscode/mytemplate
    image: ac-img:1.0.0
    container_name: ac-task
    environment:
      - ACUSER=${acUSERNAME}
      - REMOTE=${acGITREPOSITORY}
