version: "3.3"
services:
  ac-task:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - TZ=$acTIMEZONE
        - GITNAME=$acGITNAME
        - GITEMAIL=$acGITEMAIL
      # should edit workspace directory in devcontainer.json when you change USERNAME in docker
        # - USER=vscode
    tty: true
    volumes:
      - ${acSSHDIR}/.ssh:/home/vscode/.ssh:ro
      - ./scripts:/home/vscode/scripts
      - ./dotfiles/.vscode:/home/vscode/.vscode
      - ./templates/mytemplate:/home/vscode/mytemplate
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
    image: ac-img:2.2.4
    container_name: ac-task
    environment:
      - ACUSER=${acUSERNAME}
      - REMOTE=${acGITREPOSITORY}
    # command: docker run --rm ubuntu:22.04 echo 'hello from ubuntu:22.04 with docker outside of docker.'
  
  ac-runner-python:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_runner_python3
    image: ac-runner-python
    container_name: ac-runner-python
    command: python -c 'import cppyy, numpy, scipy, networkx, sympy, sortedcontainers, more_itertools, shapely, bitarray, pulp, mpmath, pandas, z3, sklearn, ortools, torch, polars, lightgbm, gmpy2, numba, atcoder' && oj --help

  ac-runner-pypy:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_runner_pypy3
    image: ac-runner-pypy
    container_name: ac-run-pypy
    command: pypy -c 'import cppyy, numpy, scipy, networkx, sympy, sortedcontainers, more_itertools, shapely, bitarray, pulp, mpmath, pandas, z3, sklearn, typing_extensions, atcoder' && oj --help

# need to update...
# volumes:
