version: "3.3"
services:
  ac-task:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        - TZ=$acTIMEZONE
        - GITNAME=$acGITNAME
        - GITEMAIL=$acGITEMAIL
      # should edit workspace directory in devcontainer.json when you change USERNAME in docker
        - USER=vscode
    tty: true
    volumes:
      # I wonder why this is working well (outside of build context...)
      - /home/kazu/.ssh:/home/vscode/.ssh:ro
      # This is not work because build context is /home/kazu/atcoder-env
      # - type: bind
      #   source: ./dotfiles/.ssh
      #   target: /home/$USER/.ssh
      #   read_only: true
      - type: bind
        source: "/var/run/docker.sock"
        target: "/var/run/docker.sock"
        read_only: true
      - type: volume
        source: atcoder
        target: /home/$USER/work
    image: ac-img:2.2.4
    container_name: ac-task
    environment:
      - ACUSER=${acUSERNAME}
      - REMOTE=${acGITREPOSITORY}
    # command: docker run --rm ubuntu:22.04 echo 'hello from ubuntu:22.04 with docker outside of docker.'
    # command: ls -la /home/vscode/work/AtCoder
  
  ac-runner-python:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_runner_python3
    image: ac-runner-python
    container_name: ac-runner-python
    command: python -c 'import cppyy, numpy, scipy, networkx, sympy, sortedcontainers, more_itertools, shapely, bitarray, pulp, mpmath, pandas, z3, sklearn, ortools, torch, polars, lightgbm, gmpy2, numba, atcoder' && oj --help
    # runner should mount volume when running container

  ac-runner-pypy:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile_runner_pypy3
    image: ac-runner-pypy
    container_name: ac-run-pypy
    command: pypy -c 'import cppyy, numpy, scipy, networkx, sympy, sortedcontainers, more_itertools, shapely, bitarray, pulp, mpmath, pandas, z3, sklearn, typing_extensions, atcoder' && oj --help
    # runner should mount volume when running container

# need to update...
# memo: 下記で全体マウントして今のディレクトリでコマンド走らせられる
# docker run --rm -it --mount type=volume,src=atcoder,dst=$HOME/work -w $(pwd) ac-runner-pypy oj t -c 'pypy main.py'

# create permanent volume
# https://zenn.dev/ajapa/articles/1369a3c0e8085d
# https://docs.docker.jp/v1.12/compose/compose-file.html#volumes-volume-driver
# https://qiita.com/gounx2/items/23b0dc8b8b95cc629f32
# https://qiita.com/aki_55p/items/63c47214cab7bcb027e0
# https://qiita.com/ymktmk/items/d32f696070490d90d218
volumes:
  atcoder:
    name: atcoder
