version: "3.8"
services:
  ac-task:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
      # should edit workspace directory in devcontainer.json when you change USERNAME
        - USERNAME=vscode
        - USERPASSWD=vscode
    tty: true
    volumes:
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh:ro
      - ${USERPROFILE-~}/work/python3/AtCoder/.git/config:/home/vscode/.gitconfig
      - ./scripts:/home/vscode/scripts
      - ./dotfiles/.vscode:/home/vscode/.vscode
    image: ac-img

